# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-18 04:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_schedule', '0007_auto_20161224_1709'),
        ('symposion_schedule', '0002_slot_name'),
    ]

    operations = [
    ]
