# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-12 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_schedule', '0009_auto_20170326_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='video_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
